params:
  input_dim: 310
  hid_dim: 64
  n_layers: 1
  beta: 0.05

setting:
  default:
    experiment_mode: subject-independent
    split_type: leave-one-out
    feature_type: de_lds
    onehot: true
  seed:
    sessions: [1]
  seediv:
    sessions: [1]

train:
  seed:
    num_classes: 3
    time_steps: 30
    batch_size: 512
    epoch_pretraining: 60
    epoch_finetuning: 100
    iteration: 7
    lr: 0.001
    weight_decay: 0.0005

  seediv:
    num_classes: 4
    time_steps: 10
    batch_size: 256
    epoch_pretraining: 60
    epoch_finetuning: 100
    iteration: 3
    lr: 0.001
    weight_decay: 0.0005